@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@defaultBaseURL = http://{{host}}

@defaultContentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

### home
GET {{defaultBaseURL}}

### get products
GET {{defaultBaseURL}}/products

### get a product 1
GET {{defaultBaseURL}}/product/1

### get a product 2
GET {{defaultBaseURL}}/product/2


### add product
POST {{defaultBaseURL}}/add_product
Content-Type: {{defaultContentType}}

{
  "id": 5,
  "name" : "test"
}

### test request
GET https://jsonplaceholder.typicode.com/todos/1

### test curl request
curl https://jsonplaceholder.typicode.com/todos/1



